### ISSUE TITLE
Question about server list

### ISSUE THREAD

**Issue by Tam66662** [sebastianhaeni/RemoteControl#1]
Hi,

I know this project of yours is pretty old, but I was wondering if you could help me figure out how to get it to run.  I am able to compile/run the server process, and I am able to run the Android App on my android device.  However, the Android App starts up and only shows "Select A Server" with no entries.  Do I have to modify a list of IP addresses somewhere, or should it automatically detect this when I start the app after the server is running?  

Here is what I see on the Android App that I have connected via USB (no servers to choose from):

![image](https://user-images.githubusercontent.com/12551526/32582945-22fcafc8-c4a6-11e7-88ce-39b1db608417.png)

And here is proof that the server is running on my PC in Visual Studio (notice the small WinForm):

![image](https://user-images.githubusercontent.com/12551526/32582988-42519ba4-c4a6-11e7-81dc-d38700ac24e8.png)

Any help would be greatly appreciated!

**Comment by sebastianhaeni** [comment]
How it works theoretically:

The server sends UDP packets on port 11111 on an interval containing the machine name. The phone picks up those messages and displays the server in the selection list. For this to work your PC and your phone need to be in the same network.

If you have another computer on hand you could start Wireshark and try to see the UDP packets on port 11111 from the remote control server once it's running.

I haven't run this for quite a while now. It may very well be that the Android app just doesn't pick up network packets anymore since they've made so many battery life improves.

Good luck! And in case you want to fix something, feel free to create a pull request.

**Comment by Tam66662** [comment]
Thanks for the reply, @sebastianhaeni .

Sorry I'm new to all of this.  Thank you for the explanation of how it's supposed to work.  I have my Android phone connected via USB to the PC that is running the remote server, but I suspect that the USB connection is only for porting the Android app, correct?  And I have both the PC and the Android phone connected to the same wi-fi network, but it's just not picking anything up.  I will try another network, as this one may be behind a firewall.  Otherwise, you may be right that the Android app just doesn't work anymore on the latest version (I'm using SDK 26, and your project was built back on version 19).

I just downloaded Wireshark (thanks for the tip!), and I can see that the PC is sending the machine name every 1 second:
![image](https://user-images.githubusercontent.com/12551526/32669149-66eee4a4-c5f4-11e7-80ab-82593c7e6728.png)

How would I use Wireshark to ensure that the Android phone is receiving these packets?  If I can get that far, I should be able to debug the rest of the way until I get it to work.

**Comment by sebastianhaeni** [comment]
I've tried out both pieces of software again. I've made some code style improvements to the server part. And I migrated the Android app to the new Gradle build system. 

For me, it works now. Maybe you had something wrong when migrating yourself? Like missing network permissions maybe?

**Comment by Tam66662** [comment]
After grabbing your latest server & app code, I can say without a doubt it is working!  

![image](https://user-images.githubusercontent.com/12551526/32681112-ad606fc4-c622-11e7-9c6a-1495eafe72ce.png)

Yeah, we can probably chalk this one up to me migrating the project incorrectly.  My bad.  Thank you very much for sharing this project, and upgrading it to SDK 26.  I will start looking into the code more to better understand the communication concept with the PC.  Appreciate all of your help! :)
